# Generated by Django 5.0.2 on 2024-03-14 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('sign_date', models.DateField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(1, 'Fri'), (2, 'Sat')], max_length=3)),
                ('transport', models.CharField(blank=True, choices=[(1, 'Plane'), (2, 'Train'), (3, 'Bus')], max_length=100)),
                ('main_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_concerts', to='modeladmin.band')),
                ('opening_band', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_conerts', to='modeladmin.band')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeladmin.band')),
                ('featuring', models.ManyToManyField(related_name='featured', to='modeladmin.band')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('state', models.CharField(choices=[('CO', 'Colarado'), ('WA', 'Washington')], max_length=2)),
                ('is_active', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField()),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='Number')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeladmin.band')),
                ('best_friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='best_friend', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationTestInlineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modeladmin.validationtestmodel')),
            ],
        ),
    ]
