# Generated by Django 5.0.2 on 2024-03-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('another_value', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(default=10)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.a')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.foo', to_field='target')),
                ('m2m_foo', models.ManyToManyField(related_name='m2m_foo', to='update.foo')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.datapoint')),
            ],
        ),
        migrations.CreateModel(
            name='UniqueNumberChild',
            fields=[
                ('uniquenumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='update.uniquenumber')),
            ],
            bases=('update.uniquenumber',),
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('c_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='update.c')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.a')),
            ],
            bases=('update.c',),
        ),
    ]
