# Generated by Django 5.0.2 on 2024-03-06 20:59

import delete.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='B1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='B2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='M2MTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delete.p')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('delete.avatar',),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('parent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete.parent')),
            ],
            bases=('delete.parent',),
        ),
        migrations.CreateModel(
            name='DeleteBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delete.b1')),
                ('b2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.b2')),
            ],
        ),
        migrations.AddField(
            model_name='b2',
            name='delete_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.deletetop'),
        ),
        migrations.AddField(
            model_name='b1',
            name='delete_top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.deletetop'),
        ),
        migrations.CreateModel(
            name='GenericB1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GenericB2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GenericDeleteBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('generic_b1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delete.genericb1')),
            ],
        ),
        migrations.CreateModel(
            name='GenericDeleteBottomParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_delete_bottom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.genericdeletebottom')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.hiddenuser')),
            ],
        ),
        migrations.CreateModel(
            name='M2MFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2m', models.ManyToManyField(to='delete.m2mto')),
            ],
        ),
        migrations.CreateModel(
            name='RChild',
            fields=[
                ('r_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete.r')),
            ],
            bases=('delete.r',),
        ),
        migrations.CreateModel(
            name='MRNull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.m')),
                ('r', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delete.r')),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.m')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.r')),
            ],
        ),
        migrations.AddField(
            model_name='m',
            name='m2m',
            field=models.ManyToManyField(related_name='m_set', to='delete.r'),
        ),
        migrations.AddField(
            model_name='m',
            name='m2m_through',
            field=models.ManyToManyField(related_name='m_through_set', through='delete.MR', to='delete.r'),
        ),
        migrations.AddField(
            model_name='m',
            name='m2m_through_null',
            field=models.ManyToManyField(related_name='m_through_null_set', through='delete.MRNull', to='delete.r'),
        ),
        migrations.AddField(
            model_name='hiddenuser',
            name='r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='delete.r'),
        ),
        migrations.CreateModel(
            name='B3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='delete.r')),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delete.r')),
            ],
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_field', models.IntegerField(unique=True)),
                ('large_field', models.TextField()),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.origin')),
            ],
        ),
        migrations.CreateModel(
            name='RelToBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rels', to='delete.base')),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.r')),
            ],
        ),
        migrations.CreateModel(
            name='SecondReferrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='delete.referrer', to_field='unique_field')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.referrer')),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.s')),
            ],
        ),
        migrations.CreateModel(
            name='U',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delete.t')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delete.avatar')),
            ],
        ),
        migrations.CreateModel(
            name='RChildChild',
            fields=[
                ('rchild_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delete.rchild')),
            ],
            bases=('delete.rchild',),
        ),
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cascade_p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cascade_p_set', to='delete.p')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_set', to='delete.r')),
                ('auto_nullable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_nullable_set', to='delete.r')),
                ('cascade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cascade_set', to='delete.r')),
                ('cascade_nullable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cascade_nullable_set', to='delete.r')),
                ('donothing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donothing_set', to='delete.r')),
                ('o2o_setnull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='o2o_nullable_set', to='delete.r')),
                ('protect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protect_set', to='delete.r')),
                ('restrict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='restrict_set', to='delete.r')),
                ('setdefault', models.ForeignKey(default=delete.models.get_default_r, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setdefault_set', to='delete.r')),
                ('setdefault_none', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='setnull_nullable_set', to='delete.r')),
                ('setnull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setnull_set', to='delete.r')),
                ('setvalue', models.ForeignKey(on_delete=models.SET(delete.models.get_default_r), related_name='setvalue', to='delete.r')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='delete.rchild')),
                ('child_setnull', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_setnull', to='delete.rchild')),
            ],
        ),
    ]
