# Generated by Django 5.0.2 on 2024-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_frosted', models.BooleanField(default=False)),
                ('has_sprinkles', models.BooleanField(null=True)),
                ('baked_date', models.DateField(null=True)),
                ('baked_time', models.TimeField(null=True)),
                ('consumed_at', models.DateTimeField(null=True)),
                ('review', models.TextField()),
            ],
            options={
                'ordering': ('consumed_at',),
            },
        ),
        migrations.CreateModel(
            name='RumBaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baked_date', models.DateField(auto_now_add=True)),
                ('baked_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
