# Generated by Django 4.1.3 on 2022-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs_db',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs_db',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
