# Generated by Django 3.1.2 on 2020-11-24 04:03

from django.db import migrations, models
import tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', tutorial.models.CurrencyField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
