# Generated by Django 5.0.2 on 2024-02-27 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('none_or_null', models.CharField(blank=True, choices=[('a', 'A'), (None, 'None'), ('', '-')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_filters.department', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_best_seller', models.BooleanField(default=0, null=True)),
                ('date_registered', models.DateField(null=True)),
                ('availability', models.BooleanField(choices=[(False, 'Paid'), (True, 'Free'), (None, 'Obscure')], null=True)),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='number')),
                ('category', models.CharField(blank=True, choices=[('non-fiction', 'Non-Fictional'), ('fiction', 'Fictional'), (None, 'Not categorized'), ('', "We don't know")], max_length=20, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_authored', to=settings.AUTH_USER_MODEL, verbose_name='Verbose Author')),
                ('contributors', models.ManyToManyField(blank=True, related_name='books_contributed', to=settings.AUTH_USER_MODEL, verbose_name='Verbose Contributors')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_filters.employee', verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ImprovedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_filters.book')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='contenttypes.contenttype')),
            ],
        ),
    ]
