# Generated by Django 4.1.3 on 2023-01-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('age',)},
        ),
    ]
