# Generated by Django 5.0.2 on 2024-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('primary_categories', models.ManyToManyField(related_name='primary_article_set', to='m2m_multiple.category')),
                ('secondary_categories', models.ManyToManyField(related_name='secondary_article_set', to='m2m_multiple.category')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
