# Generated by Django 4.1.3 on 2023-01-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfield', '0002_auto_20211205_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellocustom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
